"""create initial tables

Revision ID: 3bc39ad16e5d
Revises: 
Create Date: 2025-07-17 23:43:13.751501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc39ad16e5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=30), nullable=False),
    sa.Column('fuel_type', sa.Enum('GASOLINE', 'ETHANOL', 'DIESEL', 'ELECTRIC', 'HYBRID', name='fueltype'), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('kilometers', sa.Float(), nullable=False),
    sa.Column('number_of_doors', sa.Integer(), nullable=False),
    sa.Column('transmission', sa.Enum('MANUAL', 'AUTOMATIC', 'CVT', 'SEQUENTIAL', name='transmission'), nullable=False),
    sa.Column('wheel_size', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('SEDAN', 'HATCHBACK', 'SUV', 'WAGON', 'PICKUP', 'CONVERTIBLE', 'COUPE', name='category'), nullable=False),
    sa.Column('steering', sa.Enum('MANUAL', 'HYDRAULIC', 'ELECTRIC', name='steering'), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
